spring.application.name=moitz

spring.profiles.group.load-test=loadtest,devclient,db
spring.profiles.group.dev=dev,devclient,db
spring.profiles.group.prod=prod,client,db

spring.redis.host= 127.0.0.1
spring.redis.port= 6379
spring.redis.timeout=60000ms

dev.logging.file.debug.path=/home/ubuntu/app-logs/debug

prod.logging.file.info.path=/var/snap/amazon-ssm-agent/11798/app-logs/info
prod.logging.file.warn.path=/var/snap/amazon-ssm-agent/11798/app-logs/warn
prod.logging.file.error.path=/var/snap/amazon-ssm-agent/11798/app-logs/error

management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health,metrics
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoint.metrics.enabled=true

management.metrics.enable.jvm=true
management.metrics.enable.tomcat=true
management.metrics.distribution.percentiles.http.server.requests=0.95,0.99
management.metrics.distribution.percentiles-histogram.http.server.requests=true

server.tomcat.mbeanregistry.enabled=true
server.tomcat.accept-count=100
server.tomcat.max-connections=80
server.tomcat.threads.min-spare=10
server.tomcat.threads.max=80
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D

management.metrics.export.cloudwatch.enabled=true
management.metrics.export.cloudwatch.namespace=Moitz2025Dev
management.metrics.export.cloudwatch.step=30s
management.metrics.export.cloudwatch.region=ap-northeast-2
management.metrics.tags.app=moitz
management.metrics.tags.env=dev

spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.jmx-enabled=true

resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.configs.default.slidingWindowSize=5
resilience4j.circuitbreaker.configs.default.failureRateThreshold=60
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=30s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5

resilience4j.circuitbreaker.instances.gemini.baseConfig=default
resilience4j.circuitbreaker.instances.gemini.slidingWindowSize=1
resilience4j.circuitbreaker.instances.gemini.failureRateThreshold=50
resilience4j.circuitbreaker.instances.gemini.minimumNumberOfCalls=1
resilience4j.circuitbreaker.instances.gemini.recordExceptions=com.f12.moitz.common.error.exception.ExternalApiException
resilience4j.circuitbreaker.instances.gemini.ignoreExceptions=com.f12.moitz.common.error.exception.RetryableApiException

resilience4j.circuitbreaker.instances.geminiRetryable.baseConfig=default
resilience4j.circuitbreaker.instances.geminiRetryable.recordExceptions=com.f12.moitz.common.error.exception.RetryableApiException
resilience4j.circuitbreaker.instances.geminiRetryable.ignoreExceptions=com.f12.moitz.common.error.exception.ExternalApiException,io.github.resilience4j.circuitbreaker.CallNotPermittedException
