spring.data.mongodb.host=127.0.0.1
spring.redis.host=127.0.0.1
monitoring.namespace=Moitz2025Dev
logging.file.path=./logs

management.metrics.export.cloudwatch.enabled=false
management.metrics.tags.env=local
