name: 무중단 배포 테스트

on:
  push:
    branches:
      - zero-downtime
  workflow_dispatch:

jobs:
  deploy_prod:
    runs-on: [self-hosted, lb]

    steps:
      - name: 1단계 그린 활성화
        run: |
          echo "➡️ Green 인스턴스 부팅"
          GREEN_INSTANCE_ID=$(aws ec2 describe-instances \
            --filters 'Name=tag:ProjectTeam,Values=moitz' \
                      'Name=tag:Color,Values=green' \
            --query 'Reservations[0].Instances[0].InstanceId' \
            --output text)

          echo "::add-mask::$GREEN_INSTANCE_ID"

          if [ -z "$GREEN_INSTANCE_ID" ] || [ "$GREEN_INSTANCE_ID" == "None" ]; then
            echo "🔴 Green 인스턴스를 찾을 수 없습니다"
            exit 1
          fi

          echo GREEN_INSTANCE_ID=$GREEN_INSTANCE_ID >> $GITHUB_ENV
          aws ec2 start-instances --instance-ids $GREEN_INSTANCE_ID
          aws ec2 wait instance-status-ok --instance-ids $GREEN_INSTANCE_ID
          echo "✅ Green 인스턴스 부팅 완료"

      - name: 2단계 Blue/Green IP 가져오기 및 deploy.sh 실행
        run: |
          BLUE_INSTANCE_ID=$(aws ec2 describe-instances \
            --filters 'Name=tag:ProjectTeam,Values=moitz' \
                      'Name=tag:Color,Values=blue' \
            --query 'Reservations[0].Instances[0].InstanceId' \
            --output text)

          BLUE_INSTANCE_IP=$(aws ec2 describe-instances \
            --instance-ids $BLUE_INSTANCE_ID \
            --query "Reservations[0].Instances[0].PrivateIpAddress" \
            --output text)

          GREEN_INSTANCE_IP=$(aws ec2 describe-instances \
            --instance-ids ${{ env.GREEN_INSTANCE_ID }} \
            --query "Reservations[0].Instances[0].PrivateIpAddress" \
            --output text)

          if [ -z "$BLUE_INSTANCE_ID" ] || [ "$BLUE_INSTANCE_ID" == "None" ]; then
            echo "🔴 Blue 인스턴스를 찾을 수 없습니다"
            exit 1
          fi

          echo "::add-mask::$BLUE_INSTANCE_ID"
          echo "::add-mask::$BLUE_INSTANCE_IP"
          echo "::add-mask::$GREEN_INSTANCE_IP"
          echo BLUE_INSTANCE_ID=$BLUE_INSTANCE_ID >> $GITHUB_ENV
          echo BLUE_INSTANCE_IP=$BLUE_INSTANCE_IP >> $GITHUB_ENV
          echo GREEN_INSTANCE_IP=$GREEN_INSTANCE_IP >> $GITHUB_ENV

          echo "➡️ Green 인스턴스에서 deploy.sh 실행"
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids ${{ env.GREEN_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Run deploy.sh on Green EC2" \
            --parameters 'commands=["chmod +x /var/snap/amazon-ssm-agent/11798/deploy.sh && sudo /var/snap/amazon-ssm-agent/11798/deploy.sh"]' \
            --query "Command.CommandId" \
            --output text)

          # deploy.sh가 백그라운드 실행이라 wait command 제거하고 잠시 대기
          sleep 5
          echo "✅ deploy.sh 실행 완료"

      - name: 3단계 Green 헬스체크 및 블루와 교체
        run: |
          echo "➡️ Nginx 프록시 Green으로 변경"
          sudo sed -i "s/${{ env.BLUE_INSTANCE_IP }}/${{ env.GREEN_INSTANCE_IP }}/g" /etc/nginx/sites-available/default
          sudo nginx -t && sudo nginx -s reload
          sleep 5
          echo "✅ Nginx 프록시 변경 완료"

          echo "➡️ Blue 인스턴스 임시정지"
          aws ec2 stop-instances --instance-ids ${{ env.BLUE_INSTANCE_ID }}
          aws ec2 wait instance-stopped --instance-ids ${{ env.BLUE_INSTANCE_ID }}
          echo "✅ Blue 인스턴스 임시정지 완료"

          echo "➡️ Green/Blue 태그 교체"
          aws ec2 create-tags --resources ${{ env.GREEN_INSTANCE_ID }} --tags Key=Color,Value=blue
          aws ec2 create-tags --resources ${{ env.BLUE_INSTANCE_ID }} --tags Key=Color,Value=green
          echo "✅ 태그 교체 완료!"
